### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#109]
In GitLab by @captn3m0 on Feb 4, 2020, 12:37

After a few errors from Subsonic API, the app starts to hang, and CPU usage spikes (100%). I'm adding all of the log below, not sure which part would be helpful.

```
sublime-music
/usr/lib/python3.8/site-packages/sublime/state_manager.py:7: PyGIWarning: NetworkManager was imported without specifying a version first. Use gi.require_version('NetworkManager', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import NetworkManager, NMClient
/usr/lib/python3.8/site-packages/sublime/state_manager.py:7: PyGIWarning: NMClient was imported without specifying a version first. Use gi.require_version('NMClient', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import NetworkManager, NMClient

(sublime-music:56149): Gtk-CRITICAL **: 01:02:57.336: gtk_widget_set_size_request: assertion 'width >= -1' failed

(sublime-music:56149): Gtk-WARNING **: 01:02:57.336: gtk_widget_size_allocate(): attempt to allocate widget with width 30 and height -23
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/app.py", line 110, in do_activate
    self.state.load()
  File "/usr/lib/python3.8/site-packages/sublime/state_manager.py", line 139, in load
    CacheManager.reset(self.config, self.config.server, self.current_ssids)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 1053, in reset
    CacheManager._instance = CacheManager.__CacheManagerInternal(
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 327, in __init__
    self.load_cache_info()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 360, in load_cache_info
    self.cache[name] = [
TypeError: 'NoneType' object is not iterable
/usr/lib/python3.8/site-packages/sublime/ui/common/edit_form_dialog.py:111: DeprecationWarning: Gtk.Widget.set_margin_right is deprecated
  button.set_margin_right(10)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/app.py", line 565, in on_connected_server_changed
    self.reset_state()
  File "/usr/lib/python3.8/site-packages/sublime/app.py", line 572, in reset_state
    self.player.reset()
AttributeError: 'SublimeMusicApp' object has no attribute 'player'
2020-02-05 01:03:58,091:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f971871f3d0 state=finished raised Exception>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/albums.py", line 126, in get_genres_done
    (genre.value, genre.value) for genre in (f.result() or [])
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found
2020-02-05 01:03:58,997:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f971871f3a0 state=finished raised Exception>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found

(sublime-music:56149): Gtk-WARNING **: 01:03:59.007: actionhelper: action app.play-next can't be activated due to parameter type mismatch (parameter type as, target type NULL)

(sublime-music:56149): Gtk-WARNING **: 01:03:59.007: actionhelper: action app.add-to-queue can't be activated due to parameter type mismatch (parameter type as, target type NULL)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/albums.py", line 126, in get_genres_done
    (genre.value, genre.value) for genre in (f.result() or [])
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/common/album_with_songs.py", line 301, in update_album_songs
    GLib.Variant('as', song_ids))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 145, in _create
    builder.add_value(self._create(element_type, i))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not int
2020-02-05 01:04:18,015:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f9719779460 state=finished raised Exception>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found

(sublime-music:56149): Gtk-WARNING **: 01:04:18.041: actionhelper: action app.play-next can't be activated due to parameter type mismatch (parameter type as, target type NULL)

(sublime-music:56149): Gtk-WARNING **: 01:04:18.041: actionhelper: action app.add-to-queue can't be activated due to parameter type mismatch (parameter type as, target type NULL)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/common/album_with_songs.py", line 301, in update_album_songs
    GLib.Variant('as', song_ids))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 145, in _create
    builder.add_value(self._create(element_type, i))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not int
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/albums.py", line 126, in get_genres_done
    (genre.value, genre.value) for genre in (f.result() or [])
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/common/album_with_songs.py", line 301, in update_album_songs
    GLib.Variant('as', song_ids))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 145, in _create
    builder.add_value(self._create(element_type, i))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not int
2020-02-05 01:04:19,348:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f97186c0c40 state=finished raised Exception>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/common/album_with_songs.py", line 301, in update_album_songs
    GLib.Variant('as', song_ids))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 145, in _create
    builder.add_value(self._create(element_type, i))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not int
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/albums.py", line 126, in get_genres_done
    (genre.value, genre.value) for genre in (f.result() or [])
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 213, in <lambda>
    lambda f: after_download(f.result()))
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 206, in future_fn
    return download_fn()
  File "/usr/lib/python3.8/site-packages/sublime/cache_manager.py", line 956, in <lambda>
    lambda: self.server.get_genres().genre,
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 221, in get_genres
    result = self._get_json(self._make_url('getGenres'))
  File "/usr/lib/python3.8/site-packages/sublime/server/server.py", line 149, in _get_json
    raise Exception(f'Subsonic API Error #{code}: {message}')
Exception: Subsonic API Error #70: view not found
```

I'm running this against Gonic. The app launches, server connects but starts to give errors aftere a few clicks on Albums view.

**Comment by sumnerevans** [comment]
In GitLab by @captn3m0 on Feb 4, 2020, 12:38

Clicking the cross button, or doing a UI Kill (Alt+F4) doesn't seem to have any effect. I had to send SIGTERM from htop to terminate the application.

My CPU fan stops once I kill the app.

**Comment by sumnerevans** [comment]
Interesting. Looks like there are a few issues here.

1. It appears that maybe your config is in an invalid state. I recommend blowing away the cache (`~/.cache/sublime-music`) and config (`~/.config/sublime-music`) and the application storage (`~/.local/share/sublime-music`) and and restarting. I think that it is in a bad state is due to the other issue that you commented on. Right now, I've not really implemented a way to recover from errors like that.
2. It appears that `getGenres` is not implemented in Gonic. I have plans to make Sublime Music more resilient to unimplemented/optional fields from servers, but at the moment, things just explode.

I would definitely try (1), and then see if things improve at all (my guess is no, but we can hope). Also, if you run the latest version of Sublime Music with the `-m debug` flag:

```
sublime-music -m debug -l PATH_TO_LOGFILE
```

you will get more logs output to the logfile specified. (If you just want to output to stdout, leave off the `-l PATH_TO_LOGFILE` part.)

**Comment by sumnerevans** [comment]
Thinking about this more, I bet the reason that you are seeing the large CPU spike is that Sublime Music keeps trying to retrieve genres and can't. Each of those requests is basically another job that is put into the queue to be picked up by the thread pool, and so when you UI kill the app, the threads are still running.

**Comment by sumnerevans** [comment]
marked this issue as related to #40

**Comment by sumnerevans** [comment]
https://github.com/sentriz/gonic/issues/34

**Comment by sumnerevans** [comment]
@sentriz is adding support for Sublime Music in this branch: https://github.com/sentriz/gonic/tree/sublime

I think that everything should work after those changes. I'm going to move this back to 'Reference to deleted milestone Version 1.0' so it doesn't block this release.

**Comment by sumnerevans** [comment]
Sublime Music should be working a lot better with Gonic after the latest release by @sentriz v0.7.0 https://github.com/sentriz/gonic/releases/tag/v0.7.0. I'm going to close this for now, please re-open or create a new issue if you continue running into issues.

**Comment by sumnerevans** [comment]
closed
