### ISSUE TITLE
CacheManager failure on Debian

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#141]
In GitLab by @anarcat on Mar 27, 2020, 12:29

Hi!

First, congratulations on this awesome project. As far as I know, this the first project to attempt the implementation of a desktop client for Subsonic servers, so as such it's already an accomplishment. :)

I'm trying to build a Debian package out of this and I am having some problems. The first one is the way we talk to network manager, but I think I have fixed that in !31. We're also missing `python-mpv` from the archive but that's something we need to fix on our own. :)

The second problem, more serious, is that the client does not actually work here.

I do the following steps:

 1. configure a server
 2. click "connect"
 3. click the "Artists" tab

I see the following backtrace in the console:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime/app.py", line 790, in <lambda>
    GLib.idle_add(lambda: self.window.update(self.state, force=force))
  File "/usr/lib/python3/dist-packages/sublime/ui/main.py", line 89, in update
    active_panel.update(state, force=force)
  File "/usr/lib/python3/dist-packages/sublime/ui/artists.py", line 51, in update
    self.artist_list.update(state=state)
  File "/usr/lib/python3/dist-packages/sublime/ui/util.py", line 361, in wrapper
    **kwargs,
  File "/usr/lib/python3/dist-packages/sublime/ui/artists.py", line 122, in <lambda>
    lambda *a, **k: CacheManager.get_artists(*a, **k),
TypeError: 'NoneType' object is not callable
```

and the UI seem to be stuck endlessly refreshing the list of artists. Same when I click on the other tabs. "Browse" gives me this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime/app.py", line 790, in <lambda>
    GLib.idle_add(lambda: self.window.update(self.state, force=force))
  File "/usr/lib/python3/dist-packages/sublime/ui/main.py", line 89, in update
    active_panel.update(state, force=force)
  File "/usr/lib/python3/dist-packages/sublime/ui/browse.py", line 94, in update
    self.update_order_token,
TypeError: 'NoneType' object is not callable
```

Playlists:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime/app.py", line 790, in <lambda>
    GLib.idle_add(lambda: self.window.update(self.state, force=force))
  File "/usr/lib/python3/dist-packages/sublime/ui/main.py", line 89, in update
    active_panel.update(state, force=force)
  File "/usr/lib/python3/dist-packages/sublime/ui/playlists.py", line 67, in update
    self.playlist_list.update(state=state, force=force)
  File "/usr/lib/python3/dist-packages/sublime/ui/playlists.py", line 181, in update
    self.update_list(**kwargs)
  File "/usr/lib/python3/dist-packages/sublime/ui/util.py", line 361, in wrapper
    **kwargs,
  File "/usr/lib/python3/dist-packages/sublime/ui/playlists.py", line 184, in <lambda>
    lambda *a, **k: CacheManager.get_playlists(*a, **k),
TypeError: 'NoneType' object is not callable
```

Going back to `Albums` doesn't trigger an exception, but doesn't show albums either.

I'll also note that the "Configure servers" dialog triggers the following exception when started:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime/app.py", line 414, in on_configure_servers
    self.show_configure_servers_dialog()
  File "/usr/lib/python3/dist-packages/sublime/app.py", line 780, in show_configure_servers_dialog
    dialog = ConfigureServersDialog(self.window, self.state.config)
  File "/usr/lib/python3/dist-packages/sublime/ui/configure_servers.py", line 164, in __init__
    self.server_list_on_selected_rows_changed(None)
  File "/usr/lib/python3/dist-packages/sublime/ui/configure_servers.py", line 251, in server_list_on_selected_rows_changed
    button.set_sensitive(not requires_selection or has_selection)
TypeError: Argument 1 does not allow None as a value
```

The server list shows correctly, but even when i select a server and click "connect", the hamburger menu still says "not connected to a server" which probably explains the other errors.

I'll also note that the server list disappears after a restart, i need to reconfigure it by hand at every start.

Thanks again for your work!

**Comment by sumnerevans** [comment]
Thank you for the kind words.

A few questions:

1. When you configured the server, did you select the server before pressing "Connect"? That's required, or things will blow up spectacularly (as you can tell).
2. What version of Python are you using?
3. Can you try rebasing on the latest `master` and see if things work better? (I tried adding a cast from None to bool.)

My guess is that you were probably able to do this due to the `Argument 1 does not allow None as a value` issue...

**Comment by sumnerevans** [comment]
In GitLab by @anarcat on Mar 27, 2020, 14:20

> When you configured the server, did you select the server before pressing "Connect"? That's required, or things will blow up spectacularly (as you can tell).

Yes.

> What version of Python are you using?

Sorry, I should have made that clearer: this is Python 3.7 on Debian buster.

> Can you try rebasing on the latest `master` and see if things work better? (I tried adding a cast from None to bool.)

Yes! It does work better, thanks! :) I think this bug is closed, and I can now see my albums... AWESOME!

**Comment by sumnerevans** [comment]
In GitLab by @anarcat on Mar 27, 2020, 14:20

closed

**Comment by sumnerevans** [comment]
In GitLab by @rdiff on Apr 14, 2020, 08:27

Hi!

Thanks for amazing client, but I have same issue.

Info: Debian 10, python 3.7, clone from master and install, server Navidrome.

Change in .chache_meta file playlist: null to playlist: list and create empty playlist solve this problem.

**Comment by sumnerevans** [comment]
@rdiff, thank you for trying my client! Can you confirm you are on latest `master`? (What commit hash are you on?) I thought I fixed that issue in 7c8bb87.

**Comment by sumnerevans** [comment]
In GitLab by @rdiff on Apr 14, 2020, 09:43

last commit 0a9313de1183fd0c356b6f2c987fb0fc04656642

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sublime_music-0.9.0-py3.7.egg/sublime/app.py", line 632, in on_connected_server_changed
    self.reset_state()
  File "/usr/local/lib/python3.7/dist-packages/sublime_music-0.9.0-py3.7.egg/sublime/app.py", line 638, in reset_state
    self.state.load()
  File "/usr/local/lib/python3.7/dist-packages/sublime_music-0.9.0-py3.7.egg/sublime/state_manager.py", line 150, in load
    CacheManager.reset(self.config, self.config.server, self.current_ssids)
  File "/usr/local/lib/python3.7/dist-packages/sublime_music-0.9.0-py3.7.egg/sublime/cache_manager.py", line 1108, in reset
    current_ssids,
  File "/usr/local/lib/python3.7/dist-packages/sublime_music-0.9.0-py3.7.egg/sublime/cache_manager.py", line 331, in __init__
    self.load_cache_info()
  File "/usr/local/lib/python3.7/dist-packages/sublime_music-0.9.0-py3.7.egg/sublime/cache_manager.py", line 390, in load_cache_info
    for x in meta_json.get(name, [])
TypeError: 'NoneType' object is not iterable
```

**Comment by sumnerevans** [comment]
@rdiff can you try the latest `master` (e4ef06c)? I fixed a few things and I'm hoping that will improve the resiliency of the cache to bad data.

**Comment by sumnerevans** [comment]
In GitLab by @rdiff on Apr 14, 2020, 13:12

Yes, works fine, thanks!
