### ISSUE TITLE
Doesn't run on Fedora 31 [ValueError: Namespace NetworkManager not available]

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#165]
In GitLab by @arg274 on Apr 26, 2020, 21:45

**System details:**
 - OS: Fedora 31
 - Installation method: PyPi
 - Architecture: amd64

**Error log:**
```
Traceback (most recent call last):
  File "/home/redacted/.local/bin/sublime-music", line 11, in <module>
    load_entry_point('sublime-music==0.9.0', 'console_scripts', 'sublime-music')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/redacted/.local/lib/python3.7/site-packages/sublime/__main__.py", line 11, in <module>
    from sublime.app import SublimeMusicApp
  File "/home/redacted/.local/lib/python3.7/site-packages/sublime/app.py", line 15, in <module>
    from .dbus_manager import dbus_propagate, DBusManager
  File "/home/redacted/.local/lib/python3.7/site-packages/sublime/dbus_manager.py", line 13, in <module>
    from .state_manager import ApplicationState, RepeatType
  File "/home/redacted/.local/lib/python3.7/site-packages/sublime/state_manager.py", line 7, in <module>
    gi.require_version('NetworkManager', '1.0')
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NetworkManager not available
```

**Comment by sumnerevans** [comment]
I believe this issue should be fixed in the `v0.9.1` release which I just published to PyPi. Can you check and see if updating solves the issue?

**Comment by sumnerevans** [comment]
In GitLab by @arg274 on Apr 26, 2020, 22:54

Thanks, that fixed it. Closing the issue.

**Comment by sumnerevans** [comment]
In GitLab by @arg274 on Apr 26, 2020, 22:54

closed

**Comment by sumnerevans** [comment]
Great! Thanks for checking out the project. Please submit issues for any other problems you have.
