### ISSUE TITLE
Test with Funkwhale

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#166]
- Test with Funkwhale using their Subsonic API.
  - https://dev.funkwhale.audio/funkwhale
  - https://docs.funkwhale.audio/developers/subsonic.html?highlight=subsonic
  - There's a demo site: https://demo.funkwhale.audio/
- Get Sublime Music added to the list of applications that it works with.
  - https://funkwhale.audio/en_US/apps
  - https://docs.funkwhale.audio/users/apps.html

**Comment by sumnerevans** [comment]
Edgar Vincent tested and everything worked.

**Comment by sumnerevans** [comment]
In GitLab by @LennyPenny on Mar 9, 2021, 13:10

I'm trying to use this with funkwhale and get lots of errors (even with the demo instance): 

1. Tracks, Albums and stuff load fine
2. Playing a track does not work (no error printed to console)
3. When I seek around in a track that fails to play I get the following errors spammed in the console: 

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/dbus/manager.py", line 24, in wrapper
    function(*args)
  File "/app/lib/python3.8/site-packages/sublime_music/app.py", line 914, in on_song_scrub
    self.player_manager.seek(new_time)
  File "/app/lib/python3.8/site-packages/sublime_music/players/manager.py", line 175, in seek
    current_player.seek(position)
  File "/app/lib/python3.8/site-packages/sublime_music/players/mpv.py", line 139, in seek
    self.mpv.seek(str(position.total_seconds()), "absolute")
  File "/app/lib/python3.8/site-packages/mpv.py", line 1054, in seek
    self.command('seek', amount, reference, precision)
  File "/app/lib/python3.8/site-packages/mpv.py", line 1041, in command
    _mpv_command(self.handle, (c_char_p*len(args))(*args))
  File "/app/lib/python3.8/site-packages/mpv.py", line 133, in raise_for_ec
    raise ex(ec, *args)
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x7f230d07c1c0>, <mpv.c_char_p_Array_5 object at 0x7f23045ca940>))

```

This is the config: ![image](https://gitlab.com/sublime-music/sublime-music/uploads/82166373fef1260de8969598f7249400/image.png)

Could this be a program on my end? Latest flatpak version on fedora 33

**Comment by sumnerevans** [comment]
Hmm... that looks bad. It seems like it's an MPV issue, though. Maybe the libmpv module isn't working for the Flatpak?

**Comment by sumnerevans** [comment]
If you run the flatpak with `-m info` or `-m debug`, do you see any additional information about what is actually being played? I'm trying to figure out if MPV just fails to play the song due to some issue with MPV or because it gets the wrong URI or what.

**Comment by sumnerevans** [comment]
In GitLab by @LennyPenny on Mar 9, 2021, 15:24

Tried with -m info and these exceptions caught my eyes (note that syncying queue is off): 
```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 455, in _get
    raise ServerError(
sublime_music.adapters.subsonic.adapter.ServerError: https://demo.funkwhale.audio//rest/savePlayQueue.view returned status=404.
2021-03-09 23:21:47,241:INFO:root:adapter:Starting Exponential Backoff: n=5
2021-03-09 23:21:47,245:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f9750595cd0 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 375, in future_fn
    return fn(*params, **kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 755, in save_play_queue
    self._get(
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 455, in _get
    raise ServerError(
sublime_music.adapters.subsonic.adapter.ServerError: https://demo.funkwhale.audio//rest/savePlayQueue.view returned status=404.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 377, in future_fn
    raise CacheMissError(partial_data=partial_data) from e
sublime_music.adapters.adapter_base.CacheMissError

```

Though they only happen when clicking play+pause. For the first play click there are no exceptions thrown.
