### ISSUE TITLE
Test with LMS

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#250]
Login was fixed in e66c529, but there are other issues. I think a lot of them are due to LMS implementing the API incorrectly. A few things need to happen here:

1. figure out what's broken in Sublime Music when using LMS
2. figure out who's problem it is
3. report bugs to LMS or Sublime Music as appropriate

**Comment by sumnerevans** [comment]
In GitLab by @Glask1 on Nov 17, 2020, 16:42

Tested with lms v3.22.0 and Sublime v.0.11.10 installed via pip on void linux.

Was able to add the server, but the albums and artists screens were blank. Playlists were working and able to be played.

`
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f5f3046a5b0 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/core.py", line 263, in _decode_generic
    res = _get_type_cons(type_)(xs)
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/core.py", line 306, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/core.py", line 187, in _decode_dataclass
    init_kwargs[field.name] = overrides[field.name].decoder(
  File "/home/gary/.local/lib/python3.9/site-packages/sublime_music/adapters/subsonic/api_objects.py", line 23, in <lambda>
    timedelta: (lambda s: timedelta(seconds=s) if s else None),
TypeError: unsupported type for timedelta seconds component: str
`

It seems variable 'seconds' should be int. I was able to fix this in api_objects.py by changing line 23 to:

`timedelta: (lambda s: timedelta(seconds=int(s)) if s else None)`


Albums now load correctly but artists still dont:

`
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f8a446a97c0 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/home/gary/.local/lib/python3.9/site-packages/sublime_music/adapters/manager.py", line 375, in future_fn
    return fn(*params, **kwargs)
  File "/home/gary/.local/lib/python3.9/site-packages/sublime_music/adapters/subsonic/adapter.py", line 617, in get_artists
    if artist_index := self._get_json(self._make_url("getArtists")).artists:
  File "/home/gary/.local/lib/python3.9/site-packages/sublime_music/adapters/subsonic/adapter.py", line 508, in _get_json
    return Response.from_dict(subsonic_response)
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/api.py", line 83, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/core.py", line 273, in _decode_generic
    res = _decode_dataclass(type_arg, value, infer_missing)
  File "/home/gary/.local/lib/python3.9/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'ignored_articles'
`

The cause of this seems to be that LMS 'artists' does not have the 'ignored_articles' at all. I was able to comment out all lines that referred to 'ignored_articles' and this stopped the error. Perhaps you can deal with the case that the results from getArtists and getIndexes not returning the 'ignored_articles'.

**Comment by sumnerevans** [comment]
Thanks so much for testing! This is a lot of help.

For the first issue, I'm fine if you want to submit a patch including that `int(s)` fix. I think that it is an error with LMS, so it would be good to report there as well.

For the second issue, I think that issue should be fixed in `master`. If you can confirm it is working there, then I'll cut a new release with that fix.
