### ISSUE TITLE
Search does not return results

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#253]
In GitLab by @marcoSch on Jul 27, 2020, 08:50

When using the search bar in the top left I get no results.

I use: 
- airsonic 10.6.2
- sublime-music v0.11.1 from AUR
- Arch Linux

The following is logged:
```
(sublime-music:305053): Gtk-CRITICAL **: 16:49:31.393: gtk_widget_set_size_request: assertion 'width >= -1' failed
/usr/lib/python3.8/site-packages/sublime/ui/albums.py:266: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  self.page_entry.set_text(str(self.album_page + 1))
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/peewee.py", line 6807, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.8/site-packages/peewee.py", line 4226, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/main.py", line 1075, in _update_search_results
    if search_results.songs is not None:
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 214, in songs
    return self._to_result(
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 176, in _to_result
    all_results = sorted(
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 181, in <genexpr>
    for t in transform(x)
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 215, in <lambda>
    self._songs, lambda s: (s.title, s.artist.name if s.artist else None)
  File "/usr/lib/python3.8/site-packages/peewee.py", line 4374, in __get__
    return self.get_rel_instance(instance)
  File "/usr/lib/python3.8/site-packages/peewee.py", line 4365, in get_rel_instance
    obj = self.rel_model.get(self.field.rel_field == value)
  File "/usr/lib/python3.8/site-packages/peewee.py", line 6384, in get
    return sq.get()
  File "/usr/lib/python3.8/site-packages/peewee.py", line 6810, in get
    raise self.model.DoesNotExist('%s instance matching query does '
sublime.adapters.filesystem.models.ArtistDoesNotExist: <Model: Artist> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."album_count", "t1"."starred", "t1"."biography", "t1"."music_brainz_id", "t1"."last_fm_url", "t1"."_artist_image_url_id" FROM "artist" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: ['131', 1, 0]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/peewee.py", line 6807, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3.8/site-packages/peewee.py", line 4226, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sublime/ui/main.py", line 1075, in _update_search_results
    if search_results.songs is not None:
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 214, in songs
    return self._to_result(
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 176, in _to_result
    all_results = sorted(
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 181, in <genexpr>
    for t in transform(x)
  File "/usr/lib/python3.8/site-packages/sublime/adapters/api_objects.py", line 215, in <lambda>
    self._songs, lambda s: (s.title, s.artist.name if s.artist else None)
  File "/usr/lib/python3.8/site-packages/peewee.py", line 4374, in __get__
    return self.get_rel_instance(instance)
  File "/usr/lib/python3.8/site-packages/peewee.py", line 4365, in get_rel_instance
    obj = self.rel_model.get(self.field.rel_field == value)
  File "/usr/lib/python3.8/site-packages/peewee.py", line 6384, in get
    return sq.get()
  File "/usr/lib/python3.8/site-packages/peewee.py", line 6810, in get
    raise self.model.DoesNotExist('%s instance matching query does '
sublime.adapters.filesystem.models.ArtistDoesNotExist: <Model: Artist> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."album_count", "t1"."starred", "t1"."biography", "t1"."music_brainz_id", "t1"."last_fm_url", "t1"."_artist_image_url_id" FROM "artist" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: ['131', 1, 0]
```

**Comment by sumnerevans** [comment]
I've identified the problem, and I'm hoping to get a fix in tonight.

**Comment by sumnerevans** [comment]
Update: this is proving to be much more annoying of a fix to make. More digging is necessary to get a good solution, and this week is getting fairly busy. I'm hoping to get to this by the weekend.

**Comment by sumnerevans** [comment]
This bug should be fixed in v0.11.2

**Comment by sumnerevans** [comment]
In GitLab by @marcoSch on Aug 1, 2020, 06:06

I have just updated to v0.11.4.
I still get no result in the search bar and the same error in the log.

**Comment by sumnerevans** [comment]
Well shoot... looking...

**Comment by sumnerevans** [comment]
In GitLab by @marcoSch on Aug 1, 2020, 13:29

I can confirm, that the issue is now solved based on sublime-music-git/v0.11.6

**Comment by sumnerevans** [comment]
I just updated the AUR version to v0.11.6

**Comment by sumnerevans** [comment]
mentioned in commit a95dff751fa1012d55b4b558556860b1fcca3fc7

**Comment by sumnerevans** [comment]
mentioned in commit 121b86603c7ddbcf82c3a9c0fbf70bf095bdde36
