### ISSUE TITLE
pip install not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#262]
In GitLab by @walid.moghrabi on Aug 28, 2020, 03:39

Hi,

OS : Ubuntu 19.10
Desktop : Budgie Desktop
Python version : 3.7.5

I tried the pip installation and I get this error when trying to start sublime-music :

```bash
user@FRLM01 [~] > pip3 install sublime-music                                                                                                                                                            
Collecting sublime-music
  Downloading https://files.pythonhosted.org/packages/58/5b/4b57037b720233a3fc81be3c09f4f699242906ca89f8fb65112a9ce2994e/sublime-music-0.11.8.tar.gz (145kB)
    100% |████████████████████████████████| 153kB 1.2MB/s 
  Installing build dependencies ... done
Requirement already satisfied: dataclasses-json in ./.local/lib/python3.7/site-packages (from sublime-music) (0.5.2)
Requirement already satisfied: deepdiff in ./.local/lib/python3.7/site-packages (from sublime-music) (5.0.2)
Requirement already satisfied: fuzzywuzzy in ./.local/lib/python3.7/site-packages (from sublime-music) (0.18.0)
Requirement already satisfied: peewee in ./.local/lib/python3.7/site-packages (from sublime-music) (3.13.3)
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from sublime-music) (3.34.0)
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from sublime-music) (2.7.3)
Requirement already satisfied: python-Levenshtein in ./.local/lib/python3.7/site-packages (from sublime-music) (0.12.0)
Requirement already satisfied: python-mpv in ./.local/lib/python3.7/site-packages (from sublime-music) (0.5.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from sublime-music) (2.21.0)
Requirement already satisfied: semver in ./.local/lib/python3.7/site-packages (from sublime-music) (2.10.2)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in ./.local/lib/python3.7/site-packages (from dataclasses-json->sublime-music) (3.7.1)
Requirement already satisfied: stringcase<2.0.0,==1.2.0 in ./.local/lib/python3.7/site-packages (from dataclasses-json->sublime-music) (1.2.0)
Requirement already satisfied: typing-inspect>=0.4.0 in ./.local/lib/python3.7/site-packages (from dataclasses-json->sublime-music) (0.6.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in ./.local/lib/python3.7/site-packages (from dataclasses-json->sublime-music) (1.5.1)
Requirement already satisfied: ordered-set>=4.0.1 in ./.local/lib/python3.7/site-packages (from deepdiff->sublime-music) (4.0.2)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject->sublime-music) (1.16.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from python-Levenshtein->sublime-music) (41.1.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ./.local/lib/python3.7/site-packages (from typing-inspect>=0.4.0->dataclasses-json->sublime-music) (0.4.3)
Requirement already satisfied: typing-extensions>=3.7.4 in ./.local/lib/python3.7/site-packages (from typing-inspect>=0.4.0->dataclasses-json->sublime-music) (3.7.4.2)
Building wheels for collected packages: sublime-music
  Running setup.py bdist_wheel for sublime-music ... done
  Stored in directory: /home/user/.cache/pip/wheels/88/a2/58/5f325aeb1c4b7847b07b2032ff12f0abcd8a28de524c91db2b
Successfully built sublime-music
Installing collected packages: sublime-music
Successfully installed sublime-music-0.11.8

# starting the app
user@FRLM01 [~] > /home/user/.local/bin/sublime-music                                                                                                                                              
Traceback (most recent call last):
  File "/home/user/.local/bin/sublime-music", line 6, in <module>
    from sublime.__main__ import main
  File "/home/user/.local/lib/python3.7/site-packages/sublime/__main__.py", line 13, in <module>
    from sublime.app import SublimeMusicApp
  File "/home/user/.local/lib/python3.7/site-packages/sublime/app.py", line 132
    if icon_dir := adapter.get_ui_info().icon_dir:
                 ^
SyntaxError: invalid syntax

```

**Comment by sumnerevans** [comment]
So, the reason for this error is that Sublime Music depends on Python 3.8. That "walrus operator" is syntax introduced in Python 3.8, and I use it extensively throughout the codebase.

**Comment by sumnerevans** [comment]
In GitLab by @walid.moghrabi on Aug 28, 2020, 08:07

Well, nice, I'll upgrade my box but it's a bit arsh cause I'm pretty sure that there are a lot of people that are not always using bleeding edge setup ... and 19.10 is not that old.

**Comment by sumnerevans** [comment]
Yes, I agree it's not ideal. I'm trying to get the Flatpak or Snap working so that distros that aren't on the latest Python will work.

Also, isn't 19.10 EOL by now? They only support for 9 months, right?

**Comment by sumnerevans** [comment]
In GitLab by @walid.moghrabi on Aug 28, 2020, 10:29

EOL doesn't mean nobody is using it ... yes it is EOL but it's less than a year ago ...
Finally got it working by upgrading python to 3.8, rebuilding all the requirements and stuff ...it's working at the end but pretty painful.
You can decide to close this issue but you should mention your requirements in your Readme because unless you're running un distro with python 3.8 enabled (and there are not that much out there by now), you will have such issues.

Best regards.

**Comment by sumnerevans** [comment]
I actually have such a note in the README and the docs.

I'm going to close this for now. I'm hoping to have a working Flatpak again within a few months.

**Comment by sumnerevans** [comment]
Thanks for trying out Sublime Music, I really appreciate it!
