### ISSUE TITLE
Songs often not displayed

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#265]
In GitLab by @cr11 on Sep 22, 2020, 15:29

In the freshly built flatpak, but also with a local installation, I run into an error which prevents songs to show up when selecting an album. This doesn't happen all the time, but more often than not, and it gets likelier the more songs are in the album.  
When this happens, it just spins itself to death, leaving the field empty when leaving and reentering. Also, there is an error then, which reads:

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/ui/common/album_with_songs.py", line 338, in update_album_songs
    util.diff_song_store(self.album_song_store, new_store)
  File "/app/lib/python3.8/site-packages/sublime_music/ui/util.py", line 164, in diff_song_store
    store_to_edit.append(value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 1004, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 995, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 902, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 916, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 208, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GObject.py", line 240, in set_value
    raise TypeError("Expected string but got %s%s" %
TypeError: Expected string but got 300016807<class 'int'>
```

To elaborate on the setup, the flatpak has been derived from the **latest master** (22.9.20), but I think its also affecting earlier versions.   
The server is an **ampache** (which implements a complete subsonic api, see https://github.com/ampache/ampache/wiki/subsonic) in **4.2.2**.   
OS is **elementary 5.1**, which means ubuntu 18.04 basically.  
If you need assistance with the ampache I'd be glad to help, as I've contributed there before. The current version of **subsonic api** in Ampache is **1.13.0**.

**Comment by sumnerevans** [comment]
Hmm... I'm not being able to reproduce this myself... I wonder if this is due to slight differences in the ampache implementation of the subsonic API? 

Do you feel comfortable modifying code? If so, can you log `self.album_song_store` and `new_store` right before line 338 in `album_with_songs.py`?

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 23, 2020, 08:22

No problem, I am more into python than into flatpak :D

The print output:
```
<Gtk.ListStore object at 0x7f4dc84ea080 (GtkListStore at 0x55ce44366930)>
[[True, '', 'Hold On Tight', '3:07', '300015775']]
```

The entire output:
```
<Gtk.ListStore object at 0x7f4dc84ea080 (GtkListStore at 0x55ce44366930)>
[[True, '', 'Hold On Tight', '3:07', '300015775']]
<Gtk.ListStore object at 0x7f4dc84ea080 (GtkListStore at 0x55ce44366930)>
[[True, '', 'Hold On Tight', '3:07', 300015775]]
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/ui/common/album_with_songs.py", line 349, in update_album_songs
    self.play_next_btn.set_action_target_value(GLib.Variant("as", song_ids))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 145, in _create
    builder.add_value(self._create(element_type, i))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not int
<Gtk.ListStore object at 0x7f4dc84ea080 (GtkListStore at 0x55ce44366930)>
[[True, '', 'Hold On Tight', '3:07', 300015775]]
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/ui/common/album_with_songs.py", line 349, in update_album_songs
    self.play_next_btn.set_action_target_value(GLib.Variant("as", song_ids))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 189, in __new__
    v = creator._create(format_string, value)
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 145, in _create
    builder.add_value(self._create(element_type, i))
  File "/usr/lib/python3.8/site-packages/gi/overrides/GLib.py", line 118, in _create
    return self._LEAF_CONSTRUCTORS[format](value)
TypeError: Must be string, not int
```
Yes, it happens multiple times.

**Edit:**
I just realized, the value is a string the first time, but after that it becomes an int... Thats weird

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 24, 2020, 03:54

Out of this result, I comprised a very crude hotfix by converting the id always into string:

from `album_with_songs.py` 326ff:
```
                new_store.append(
                    [
                        playable,
                        status,
                        util.esc(song.title),
                        util.format_song_duration(song.duration),
                        str(song.id),
                    ]
```

This fixes it

**Comment by sumnerevans** [comment]
Yes, that will fix it, but the fundamental problem is that ampache sends integers instead of strings for the song ID. I'm worried there will be other instances where this bug will occur.

Can you try the `265-fix-int-ids` branch and see if it works there as well? You may have to clear your cache. I moved the stringify code to the adapter so that all of the IDs in Sublime Music will be strings.

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 24, 2020, 09:26

I tried it, it fixes all errors related to it, actually even a few more. I also took the freedom to log when such a conversion to string takes place, and it happens very frequently, so your right, ampache is sending this in an at least inconsistent, at worst wrong format. I will ask over there if there is a reason behind it, maybe this can be fixed on their side in the long run.

**Comment by sumnerevans** [comment]
Yes, they are not compliant with the spec. All of the IDs are strings (except for music folders). I'd appreciate if you could open an issue with ampache. Please link it here.

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 24, 2020, 10:04

of course, I will keep a look on it, thank you for helping out so quickly!
The issue is filed here:
https://github.com/ampache/ampache/issues/2553

**Comment by sumnerevans** [comment]
In GitLab by @lachlan-00 on Sep 24, 2020, 16:24

Hey i see that this is json specific and can fix it easily but i can't find any json example files to compare against.

on the subsonic api site it looks like everything is a string http://www.subsonic.org/pages/inc/api/examples/directory_example_2.xml

is this correct for json too?

-- edit
fixed
