### ISSUE TITLE
Caching/Saving offline not possible

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#269]
In GitLab by @cr11 on Sep 24, 2020, 10:41

Whenever booting the app up (as a flatpak), caching does not work, meaning that everything gets downloaded anew. Saving files for offline for later is forgotten after the app is closed and it even sometimes, when enough songs are selected, causes the entire PC to freeze up.  
The reason for this is very likely associated with this error message showing up whenever the app is booted. Unfortunately I don't quite understand what this exception indicates.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 612, in cache_miss_result
    raise CacheMissError(partial_data=partial_data)
sublime_music.adapters.adapter_base.CacheMissError
/app/lib/python3.8/site-packages/sublime_music/ui/albums.py:270: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  self.page_entry.set_text(str(self.album_page + 1))
ERROR:concurrent.futures:exception calling callback for <Future at 0x7f620430af70 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 612, in cache_miss_result
    raise CacheMissError(partial_data=partial_data)
sublime_music.adapters.adapter_base.CacheMissError
```

**Comment by sumnerevans** [comment]
I'm not being able to reproduce this. I am betting this is a flatpak permission issue. Can you make sure that you aren't blocking any permissions for Sublime Music using something like Flaseal?

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 24, 2020, 11:36

Youre right!  
Filesystem permission to everything fixed it. Is there something I should be aware of when installing, or should the flatpak file be tweaked accordingly?  
Anyway, thanks for responding so quickly, this and the missing songs made the app nearly unusable, now it's working pretty well!

**Comment by sumnerevans** [comment]
I don't think that the flatpak file needs to be updated. I already request permission to access the filesystem: https://gitlab.com/sublime-music/sublime-music/-/blob/master/flatpak/app.sublimemusic.SublimeMusic.json#L25

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 24, 2020, 12:17

hm, strange, the mentioned permission is actually there, but the error nevertheless occured. It also still happened when I gave permission to the homefolder. only giving permission to system fixed it...

**Comment by sumnerevans** [comment]
Hmm... maybe this is due to it needing access to `/tmp` as well? I'll look into it.
