### ISSUE TITLE
Album Cover not always loading

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#270]
In GitLab by @cr11 on Sep 25, 2020, 10:51

Showing an album cover is not always successful; around 5% of the time (so about once or twice on every album page for example) the image loading ends with an error (on the server, these albums have a cover that is also displayed successfully):

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/ui/albums.py", line 845, in on_artwork_downloaded
    artwork.set_from_file(filename.result())
  File "/app/lib/python3.8/site-packages/sublime_music/ui/common/spinner_image.py", line 37, in set_from_file
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(
gi.repository.GLib.Error: gdk-pixbuf-error-quark: Das Format der Bilddatei »/tmp/tmpdjtxn01y/4ee0bfc74268bbac9d27abed5d03882a643145ac« konnte nicht erkannt werden (3)
```
(translation of the final error: format of the image file ... could not be recognized)

To investigate the situation I copied out the file in question and realized that they were simply empty files (0 Byte), so no wonder the image could not be recognized. The Subsonic API however was always successful on sending the images to the DSub android client. Maybe you have an idea how this happens? Let me know if you need further info/debugging, I'm not entirely sure where to search for the error.  

Server is Ampache 4.2.2 with Subsonic API version 1.13.0,
Client is flatpak built from latest master.

**Comment by sumnerevans** [comment]
This sounds like an issue much further down the stack. My guess is that the download failed for some reason, but the error wasn't identified and then it just tried to use the empty file.

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 27, 2020, 07:29

Ok, you may close this issue, this is an error on the server side. It returns a 200, but a content length of 0 and of course no data, so sublime is working as expected

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 27, 2020, 07:39

Now I got whats happening here: This return means that there is no cover art available for that album. Could you maybe elaborate what should happen when the server has no cover art (meaning, what should the request actually return). Then I can open an issue on the ampache side with a very precise error and solution.

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 27, 2020, 07:58

And also, what are the possibilities to clear the cache? I dont want to clear the entire folder to not loose the offline saved songs, but can I simply delete the cover images to redownload them?

**Comment by sumnerevans** [comment]
You can just delete the `~/.local/share/sublime-music/*/c/cover_art` directory.

**Comment by sumnerevans** [comment]
If it just errors with 404 or some other non-200 error code, I think that Sublime Music should handle that properly.

**Comment by sumnerevans** [comment]
@cr11, can you try the `270-check-total-size` branch? Do you still get the same errors?

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 27, 2020, 08:37

No, now I get 'no data sent by server'

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 27, 2020, 13:20

Good, I forwarded that here:
https://github.com/ampache/ampache/issues/2557

**Comment by sumnerevans** [comment]
In GitLab by @cr11 on Sep 27, 2020, 13:27

Although, for a more consistent solution... Could you maybe check what a subsonic server answers in such a case?

**Comment by sumnerevans** [comment]
Ok, does it show a placeholder album artwork in this situation?

**Comment by sumnerevans** [comment]
Ok. Just tried it and what Airsonic does is return a JSON object similar to the following:

```
{
   "subsonic-response" : {
      "status" : "failed",
      "version" : "1.15.0",
      "error" : {
         "code" : 0,
         "message" : "For input string: \"123123123123\""
      }
   }
}
```

**Comment by sumnerevans** [comment]
In GitLab by @tommyalatalo on Jan 21, 2022, 07:39

Has there been any progress on this?
I'm also finding that a lot of times I don't get album covers loading, the music plays just fine though.
My media source is Navidrome and I'm running the Sublime (0.11.16) on Arch.
