### ISSUE TITLE
Cant connect to my airsonic-advanced server

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#279]
In GitLab by @racuna on Nov 5, 2020, 03:13

Hi, I installed sublime-music on a python3.8 conda environment in Ubuntu 18.04. Now I am trying to connect to my airsonic-advanced server (docker snapshot 11.0.0-SNAPSHOT.20201002122917) which address I write in the field server address like this: 

    http://www.myserver.com:4040

I know that the password and the username are correct since I can login in through a browser.

If I leave the Advanced settings as default the error is:

    Error connecting to the server. Error 40: Wrong username and password.

with Verify Certificate turned off or Sync Play Queue turned off:

    Error connecting to the server. Error 40: Wrong username and password.

with Use Salt Authentification turned off:

    HTTPConnectionPool(host='www.myserver.com', port=4040): Read timed out. (read timeout=2)

    
Any idea what could be happening?

**Comment by sumnerevans** [comment]
Hmm... Maybe my salt/hash logic is incorrect? It seems to be working on other servers, though.

If you run Sublime Music with debug level DEBUG, you will get *very* verbose output, and that will include the full data in the URLs that get requested:

```
sublime-music -m DEBUG
```

If you are able to, it would be good to see what the error is in the logs (be sure to anonymize the private fields in the URL). You can try to request to the same url using `curl` or similar.

I will try to reproduce this issue as well when I can, but I've been fairly busy lately.

Thanks for checking the project!

**Comment by sumnerevans** [comment]
In GitLab by @racuna on Nov 16, 2020, 03:08

Thanks for your reply.

I tried again with "Use Salt Authentification" turned off and the rest of the options ON and now it connects, I guess I did not try that specific combination. However, now it gives me the following error:

        2020-11-16 11:03:47,154:ERROR:root:config:Couldn't load state from /home/username/.local/share/sublime-music/73bc9384-37d6-413f-9f59-0807aa889c7b/state.pickle
        Traceback (most recent call last):
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/sublime_music/config.py", line 215, in load_state
            self._state = pickle.load(f)
        EOFError: Ran out of input
        2020-11-16 11:03:47,154:INFO:root:app:Updating window force=True
        2020-11-16 11:03:47,157:DEBUG:peewee:peewee:('BEGIN', None)
        2020-11-16 11:03:47,157:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "cacheinfo" ("id" INTEGER NOT NULL PRIMARY KEY, "valid" INTEGER NOT NULL, "cache_key" TEXT NOT NULL, "parameter" TEXT, "last_ingestion_time" TEXT NOT NULL, "file_id" TEXT, "file_hash" TEXT, "size" INTEGER, "path" TEXT, "cache_permanently" INTEGER)', [])
        2020-11-16 11:03:47,158:DEBUG:peewee:peewee:('CREATE UNIQUE INDEX IF NOT EXISTS "cacheinfo_cache_key_parameter" ON "cacheinfo" ("cache_key", "parameter")', [])
        2020-11-16 11:03:47,158:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "artist" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT, "album_count" INTEGER, "starred" TEXT, "biography" TEXT, "music_brainz_id" TEXT, "last_fm_url" TEXT, "_artist_image_url_id" INTEGER, FOREIGN KEY ("_artist_image_url_id") REFERENCES "cacheinfo" ("id"))', [])
        2020-11-16 11:03:47,158:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "artist__artist_image_url_id" ON "artist" ("_artist_image_url_id")', [])
        2020-11-16 11:03:47,158:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "genre" ("name" TEXT NOT NULL PRIMARY KEY, "song_count" INTEGER, "album_count" INTEGER)', [])
        2020-11-16 11:03:47,159:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "album" ("id" TEXT NOT NULL PRIMARY KEY, "created" TEXT, "duration" REAL, "name" TEXT, "play_count" INTEGER, "song_count" INTEGER, "starred" TEXT, "year" INTEGER, "artist_id" TEXT, "genre_id" TEXT, "_cover_art_id" INTEGER, FOREIGN KEY ("artist_id") REFERENCES "artist" ("id"), FOREIGN KEY ("genre_id") REFERENCES "genre" ("name"), FOREIGN KEY ("_cover_art_id") REFERENCES "cacheinfo" ("id"))', [])
        2020-11-16 11:03:47,159:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "album_artist_id" ON "album" ("artist_id")', [])
        2020-11-16 11:03:47,159:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "album_genre_id" ON "album" ("genre_id")', [])
        2020-11-16 11:03:47,159:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "album__cover_art_id" ON "album" ("_cover_art_id")', [])
        2020-11-16 11:03:47,159:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "albumqueryresult" ("query_hash" TEXT NOT NULL PRIMARY KEY)', [])
        2020-11-16 11:03:47,159:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "albumqueryresult_album_through" ("id" INTEGER NOT NULL PRIMARY KEY, "albumqueryresult_id" TEXT NOT NULL, "album_id" TEXT NOT NULL, "position" INTEGER NOT NULL, FOREIGN KEY ("albumqueryresult_id") REFERENCES "albumqueryresult" ("query_hash"), FOREIGN KEY ("album_id") REFERENCES "album" ("id"))', [])
        2020-11-16 11:03:47,160:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "albumqueryresultalbumthrough_albumqueryresult_id" ON "albumqueryresult_album_through" ("albumqueryresult_id")', [])
        2020-11-16 11:03:47,160:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "albumqueryresultalbumthrough_album_id" ON "albumqueryresult_album_through" ("album_id")', [])
        2020-11-16 11:03:47,160:DEBUG:peewee:peewee:('CREATE UNIQUE INDEX IF NOT EXISTS "albumqueryresultalbumthrough_albumqueryresult_id_album_i_a4f72d2" ON "albumqueryresult_album_through" ("albumqueryresult_id", "album_id", "position")', [])
        2020-11-16 11:03:47,160:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "directory" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT, "parent_id" TEXT)', [])
        2020-11-16 11:03:47,160:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "ignoredarticle" ("name" TEXT NOT NULL PRIMARY KEY)', [])
        2020-11-16 11:03:47,160:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "playlist" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL, "comment" TEXT, "owner" TEXT, "song_count" INTEGER, "duration" REAL, "created" TEXT, "changed" TEXT, "public" INTEGER, "_cover_art_id" INTEGER, FOREIGN KEY ("_cover_art_id") REFERENCES "cacheinfo" ("id"))', [])
        2020-11-16 11:03:47,161:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "playlist__cover_art_id" ON "playlist" ("_cover_art_id")', [])
        2020-11-16 11:03:47,161:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "song" ("id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "duration" REAL, "parent_id" TEXT, "album_id" TEXT, "artist_id" TEXT, "genre_id" TEXT, "file_id" INTEGER, "_cover_art_id" INTEGER, "track" INTEGER, "disc_number" INTEGER, "year" INTEGER, "user_rating" INTEGER, "starred" TEXT, FOREIGN KEY ("album_id") REFERENCES "album" ("id"), FOREIGN KEY ("artist_id") REFERENCES "artist" ("id"), FOREIGN KEY ("genre_id") REFERENCES "genre" ("name"), FOREIGN KEY ("file_id") REFERENCES "cacheinfo" ("id"), FOREIGN KEY ("_cover_art_id") REFERENCES "cacheinfo" ("id"))', [])
        2020-11-16 11:03:47,161:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "song_album_id" ON "song" ("album_id")', [])
        2020-11-16 11:03:47,161:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "song_artist_id" ON "song" ("artist_id")', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "song_genre_id" ON "song" ("genre_id")', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "song_file_id" ON "song" ("file_id")', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "song__cover_art_id" ON "song" ("_cover_art_id")', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "playlist_song_through" ("id" INTEGER NOT NULL PRIMARY KEY, "playlist_id" TEXT NOT NULL, "song_id" TEXT NOT NULL, "position" INTEGER NOT NULL, FOREIGN KEY ("playlist_id") REFERENCES "playlist" ("id"), FOREIGN KEY ("song_id") REFERENCES "song" ("id"))', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "playlistsongthrough_playlist_id" ON "playlist_song_through" ("playlist_id")', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "playlistsongthrough_song_id" ON "playlist_song_through" ("song_id")', [])
        2020-11-16 11:03:47,162:DEBUG:peewee:peewee:('CREATE UNIQUE INDEX IF NOT EXISTS "playlistsongthrough_playlist_id_song_id_position" ON "playlist_song_through" ("playlist_id", "song_id", "position")', [])
        2020-11-16 11:03:47,163:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "similarartist" ("id" INTEGER NOT NULL PRIMARY KEY, "artist_id" TEXT NOT NULL, "similar_artist_id" TEXT NOT NULL, "order" INTEGER NOT NULL, FOREIGN KEY ("artist_id") REFERENCES "artist" ("id"), FOREIGN KEY ("similar_artist_id") REFERENCES "artist" ("id"))', [])
        2020-11-16 11:03:47,163:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "similarartist_artist_id" ON "similarartist" ("artist_id")', [])
        2020-11-16 11:03:47,163:DEBUG:peewee:peewee:('CREATE INDEX IF NOT EXISTS "similarartist_similar_artist_id" ON "similarartist" ("similar_artist_id")', [])
        2020-11-16 11:03:47,163:DEBUG:peewee:peewee:('CREATE UNIQUE INDEX IF NOT EXISTS "similarartist_artist_id_similar_artist_id_order" ON "similarartist" ("artist_id", "similar_artist_id", "order")', [])
        2020-11-16 11:03:47,163:DEBUG:peewee:peewee:('CREATE TABLE IF NOT EXISTS "version" ("id" INTEGER NOT NULL PRIMARY KEY, "major" INTEGER NOT NULL, "minor" INTEGER NOT NULL, "patch" INTEGER NOT NULL)', [])
        Non-C locale detected. This is not supported.
        Call 'setlocale(LC_NUMERIC, "C");' in your code.
        Segmentation fault (core dumped)

**Comment by sumnerevans** [comment]
In GitLab by @racuna on Nov 16, 2020, 03:27

It works if I use: 

    LC_NUMERIC=C sublime-music


And now I have the following problem which I think it has to do with my conda environment:

        Traceback (most recent call last):
          File "/home/usrname/anaconda3/envs/sublime-music/lib/python3.8/site-packages/mpv.py", line 254, in _event_generator
            raise StopIteration()
        StopIteration

        The above exception was the direct cause of the following exception:

        Traceback (most recent call last):
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/asyncio/events.py", line 81, in _run
            self._context.run(self._callback, *self._args)
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/mpv.py", line 278, in mpv_event_extractor
            for event in _event_generator(self.handle):
        RuntimeError: generator raised StopIteration
        Traceback (most recent call last):
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/sublime_music/app.py", line 319, in do_activate
            self.player_manager = PlayerManager(
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/sublime_music/players/manager.py", line 58, in __init__
        2020-11-16 11:26:02,970:ERROR:asyncio:base_events:Exception in callback MPV.__init__.<locals>.mpv_event_extractor() at /home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/mpv.py:276
        handle: <Handle MPV.__init__.<locals>.mpv_event_extractor() at /home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/mpv.py:276>
        Traceback (most recent call last):
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/mpv.py", line 254, in _event_generator
            raise StopIteration()
        StopIteration

        The above exception was the direct cause of the following exception:

        Traceback (most recent call last):
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/asyncio/events.py", line 81, in _run
            self._context.run(self._callback, *self._args)
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/mpv.py", line 278, in mpv_event_extractor
            for event in _event_generator(self.handle):
        RuntimeError: generator raised StopIteration
            self.players = {
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/sublime_music/players/manager.py", line 59, in <dictcomp>
            player_type: player_type(
          File "/home/username/anaconda3/envs/sublime-music/lib/python3.8/site-packages/sublime_music/players/mpv.py", line 46, in __init__
            @self.mpv.property_observer("time-pos")
        AttributeError: 'MPV' object has no attribute 'property_observer'









In order to install sublime-music I followed these steps:

    conda create --name sublime-music python=3.8
    conda activate sublime-music
    sudo apt install libgirepository1.0-dev
    sudo apt install libmpv1 libmpv-dev
    pip install mpv
    pip install sublime-music[keyring,chromecast,server]

I think I messed up the mpv installation. Any idea how to solve it?

**Comment by sumnerevans** [comment]
In GitLab by @racuna on Nov 16, 2020, 04:03

Well, I gave up with the conda environment. I installed flatpack on my system and now it works. Thanks for the work on this project! I like it.

**Comment by sumnerevans** [comment]
@racuna ah, glad you were able to get it running. Python's dependency management is sometimes a real pain.

I'm going to go ahead and close this since it seems to be an environment issue rather than an issue with Sublime Music.

Thanks again for checking out the project. If you don't mind, how did you find the project?

**Comment by sumnerevans** [comment]
In GitLab by @racuna on Nov 17, 2020, 02:58

I found it in Reddit: https://www.reddit.com/r/airsonic/comments/hpgidp/sublime_music_a_linux_subsonic_client_beta/

Thanks for your help and your work on this. I have another question but I will create a separate issue for that.
