### ISSUE TITLE
Error on play when connected to funkwhale

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#306]
In GitLab by @Sleuth56 on May 8, 2021, 14:44

I just downloaded the flatpak version of Sublime music and connected it to my funkwhale instance. It got the music loaded just fine but when I try to play it I get these errors.

Funkwhale output.
```
2021-05-08 20:30:25,045 django.request WARNING  Not Found: /api/subsonic/rest/savePlayQueue.view
2021-05-08 20:30:25,275 django.request WARNING  Not Found: /api/subsonic/rest/download.view
```

Sublime Music output.
```
2021-05-08 16:39:36,233:ERROR:root:adapter:[FAIL] get: https://media.example.com/rest/savePlayQueue.view failed
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 455, in _get
    raise ServerError(
sublime_music.adapters.subsonic.adapter.ServerError: https://media.example.com/rest/savePlayQueue.view returned status=404.
2021-05-08 16:39:36,237:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f3e6cc99610 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 375, in future_fn
    return fn(*params, **kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 755, in save_play_queue
    self._get(
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 455, in _get
    raise ServerError(
sublime_music.adapters.subsonic.adapter.ServerError: https://media.example.com/rest/savePlayQueue.view returned status=404.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 377, in future_fn
    raise CacheMissError(partial_data=partial_data) from e
sublime_music.adapters.adapter_base.CacheMissError
```

**Comment by sumnerevans** [comment]
Does funkwhale not allow downloads over the subsonic API?

**Comment by sumnerevans** [comment]
In GitLab by @Sleuth56 on May 9, 2021, 24:20

It appears from both reading the docs and asking in the community that no it does not support downloads. https://docs.funkwhale.audio/developers/subsonic.html?highlight=subsonic
https://dev.funkwhale.audio/funkwhale/funkwhale/blob/develop/api/funkwhale_api/subsonic/views.py

**Comment by sumnerevans** [comment]
Hmm... what happens if you disable the "Allow Song Downloads" option in the settings?

Also, Sublime Music should try to stream instead, and that is supported by funkwhale. Are there any logs on funkwhale's side regarding the stream?

**Comment by sumnerevans** [comment]
In GitLab by @Sleuth56 on May 9, 2021, 12:57

I tried with downloads disabled and there was some progress.
This is the only thing that funkwhale has in it's logs.
`2021-05-09 18:53:08,041 django.request WARNING  Not Found: /api/subsonic/rest/savePlayQueue.view`
```
2021-05-09 14:53:08,051:ERROR:root:adapter:[FAIL] get: https://media.example.com/rest/savePlayQueue.view failed
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 455, in _get
    raise ServerError(
sublime_music.adapters.subsonic.adapter.ServerError: https://media.example.com/rest/savePlayQueue.view returned status=404.
2021-05-09 14:53:08,060:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f6b71518a90 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 375, in future_fn
    return fn(*params, **kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 755, in save_play_queue
    self._get(
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 455, in _get
    raise ServerError(
sublime_music.adapters.subsonic.adapter.ServerError: https://media.example.com/rest/savePlayQueue.view returned status=404.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 125, in _on_future_complete
    raise e
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 120, in _on_future_complete
    self._data = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 377, in future_fn
    raise CacheMissError(partial_data=partial_data) from e
sublime_music.adapters.adapter_base.CacheMissError
```

**Comment by sumnerevans** [comment]
In GitLab by @Sleuth56 on Aug 22, 2021, 20:26

I'm not certain what's different now but funkwhale works. So I'm closing this issue.
