### ISSUE TITLE
TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#325]
In GitLab by @baldurmen on Nov 4, 2021, 20:40

I was getting bug #320 on Debian Sid. Upgrading the Debian package to 11.14.0 (and thus using patch !68), I get this new error when trying to run the testsuite.

```
____________________________ test_json_load_unload _____________________________

config_filename = PosixPath('/tmp/pytest-of-emiliano/pytest-0/test_json_load_unload0/config.json')
tmp_path = PosixPath('/tmp/pytest-of-emiliano/pytest-0/test_json_load_unload0')

    def test_json_load_unload(config_filename: Path, tmp_path: Path):
        ConfigurationStore.MOCK = True
        subsonic_config_store = ConfigurationStore(username="test")
        subsonic_config_store.set_secret("password", "testpass")
        original_config = AppConfiguration(
            providers={
                "1": ProviderConfiguration(
                    id="1",
                    name="foo",
                    ground_truth_adapter_type=SubsonicAdapter,
                    ground_truth_adapter_config=subsonic_config_store,
                    caching_adapter_type=FilesystemAdapter,
                    caching_adapter_config=ConfigurationStore(),
                )
            },
            current_provider_id="1",
            filename=config_filename,
        )
        original_config.cache_location = tmp_path
    
>       original_config.save()

tests/config_test.py:64: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sublime_music/config.py:246: in save
    json = self.to_json(indent=2, sort_keys=True)
/usr/lib/python3/dist-packages/dataclasses_json/api.py:49: in to_json
    return json.dumps(self.to_dict(encode_json=False),
/usr/lib/python3/dist-packages/dataclasses_json/api.py:85: in to_dict
    return _asdict(self, encode_json=encode_json)
/usr/lib/python3/dist-packages/dataclasses_json/core.py:346: in _asdict
    return _encode_overrides(dict(result), _user_overrides_or_exts(obj),
/usr/lib/python3/dist-packages/dataclasses_json/core.py:110: in _encode_overrides
    v = encoder(v) if encoder is not None else v
sublime_music/config.py:71: in encode_providers
    return {
sublime_music/config.py:73: in <dictcomp>
    **(config if isinstance(config, dict) else asdict(config)),
/usr/lib/python3.9/dataclasses.py:1075: in asdict
    return _asdict_inner(obj, dict_factory)
/usr/lib/python3.9/dataclasses.py:1082: in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = ConfigurationStore(password=['plaintext', 'testpass'], salt_auth=True, username='test')
dict_factory = <class 'dict'>

    def _asdict_inner(obj, dict_factory):
        if _is_dataclass_instance(obj):
            result = []
            for f in fields(obj):
                value = _asdict_inner(getattr(obj, f.name), dict_factory)
                result.append((f.name, value))
            return dict_factory(result)
        elif isinstance(obj, tuple) and hasattr(obj, '_fields'):
            # obj is a namedtuple.  Recurse into it, but the returned
            # object is another namedtuple of the same type.  This is
            # similar to how other list- or tuple-derived classes are
            # treated (see below), but we just need to create them
            # differently because a namedtuple's __init__ needs to be
            # called differently (see bpo-34363).
    
            # I'm not using namedtuple's _asdict()
            # method, because:
            # - it does not recurse in to the namedtuple fields and
            #   convert them to dicts (using dict_factory).
            # - I don't actually want to return a dict here.  The main
            #   use case here is json.dumps, and it handles converting
            #   namedtuples to lists.  Admittedly we're losing some
            #   information here when we produce a json list instead of a
            #   dict.  Note that if we returned dicts here instead of
            #   namedtuples, we could no longer call asdict() on a data
            #   structure where a namedtuple was used as a dict key.
    
            return type(obj)(*[_asdict_inner(v, dict_factory) for v in obj])
        elif isinstance(obj, (list, tuple)):
            # Assume we can create an object of this type by passing in a
            # generator (which is not true for namedtuples, handled
            # above).
            return type(obj)(_asdict_inner(v, dict_factory) for v in obj)
        elif isinstance(obj, dict):
>           return type(obj)((_asdict_inner(k, dict_factory),
                              _asdict_inner(v, dict_factory))
                             for k, v in obj.items())
E           TypeError: __init__() takes 1 positional argument but 2 were given

/usr/lib/python3.9/dataclasses.py:1112: TypeError
```

Once built, I get this error when I'm trying to add a new server:

```
2021-11-04 22:32:33,283:WARNING:root:adapter:Salted auth not supported, falling back to regular password auth
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 167, in do_activate
    self.show_configure_servers_dialog()
  File "/usr/lib/python3/dist-packages/sublime_music/app.py", line 1019, in show_configure_servers_dialog
    self.app_config.save()
  File "/usr/lib/python3/dist-packages/sublime_music/config.py", line 246, in save
    json = self.to_json(indent=2, sort_keys=True)
  File "/usr/lib/python3/dist-packages/dataclasses_json/api.py", line 49, in to_json
    return json.dumps(self.to_dict(encode_json=False),
  File "/usr/lib/python3/dist-packages/dataclasses_json/api.py", line 85, in to_dict
    return _asdict(self, encode_json=encode_json)
  File "/usr/lib/python3/dist-packages/dataclasses_json/core.py", line 346, in _asdict
    return _encode_overrides(dict(result), _user_overrides_or_exts(obj),
  File "/usr/lib/python3/dist-packages/dataclasses_json/core.py", line 110, in _encode_overrides
    v = encoder(v) if encoder is not None else v
  File "/usr/lib/python3/dist-packages/sublime_music/config.py", line 71, in encode_providers
    return {
  File "/usr/lib/python3/dist-packages/sublime_music/config.py", line 73, in <dictcomp>
    **(config if isinstance(config, dict) else asdict(config)),
  File "/usr/lib/python3.9/dataclasses.py", line 1075, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/lib/python3.9/dataclasses.py", line 1082, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
  File "/usr/lib/python3.9/dataclasses.py", line 1112, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by sumnerevans** [comment]
This is also blocking releasing on NixOS.
