### ISSUE TITLE
Problem Connecting to Nextcloud Music Server

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#338]
In GitLab by @AgileFox on Apr 5, 2022, 03:41

Server: Nextcloud Music

The sublime client is getting html back from the server for some reason, but this nextcloud music server instance works with other subsonic clients without issue, so I don't know what to try next. Here is the first stack trace below. Does anyone have thoughts?

```
(sublime-music:294300): Gtk-CRITICAL **: 04:23:21.599: gtk_widget_set_size_request: assertion 'width >= -1' failed
/home/username/.local/lib/python3.8/site-packages/secretstorage/util.py:46: UserWarning: Passing unwrap= to .send_and_get_reply() is deprecated and will break in a future version of Jeepney.
  return self._connection.send_and_get_reply(msg, unwrap=True)
/home/username/.local/lib/python3.8/site-packages/sublime_music/ui/albums.py:270: Warning: g_value_get_int: assertion 'G_VALUE_HOLDS_INT (value)' failed
  self.page_entry.set_text(str(self.album_page + 1))

(sublime-music:294300): Gtk-WARNING **: 04:23:22.204: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node flowboxchild, owner GtkFlowBoxChild)

(sublime-music:294300): Gtk-WARNING **: 04:23:22.204: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node flowboxchild, owner GtkFlowBoxChild)

(sublime-music:294300): Gtk-WARNING **: 04:23:22.204: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node flowboxchild, owner GtkFlowBoxChild)

(sublime-music:294300): Gtk-WARNING **: 04:23:22.204: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node flowboxchild, owner GtkFlowBoxChild)

(sublime-music:294300): Gtk-WARNING **: 04:23:22.204: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node flowboxchild, owner GtkFlowBoxChild)
/home/username/.local/lib/python3.8/site-packages/secretstorage/util.py:46: UserWarning: Passing unwrap= to .send_and_get_reply() is deprecated and will break in a future version of Jeepney.
  return self._connection.send_and_get_reply(msg, unwrap=True)

(sublime-music:294300): Gtk-CRITICAL **: 04:23:47.440: gtk_entry_set_text: assertion 'text != NULL' failed

(sublime-music:294300): Gtk-CRITICAL **: 04:23:47.441: gtk_entry_set_text: assertion 'text != NULL' failed
2022-04-05 04:23:56,108:ERROR:concurrent.futures:_base:exception calling callback for <Future at 0x7f7c241c7070 state=finished raised CacheMissError>
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/lib/python3.8/site-packages/sublime_music/adapters/manager.py", line 375, in future_fn
    return fn(*params, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 763, in get_genres
    if genres := self._get_json(self._make_url("getGenres")).genres:
  File "/home/username/.local/lib/python3.8/site-packages/sublime_music/adapters/subsonic/adapter.py", line 517, in _get_json
    subsonic_response = result.json().get("subsonic-response")
  File "/home/username/.local/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 

<!-- NEXTCLOUD SERVER LOGIN PAGE HTML DOCUMENT LOADED HERE FROM THE SERVER -->
```

**Comment by sumnerevans** [comment]
In GitLab by @benklaasen on Jun 5, 2022, 07:10

Did you manage to sort this out?

Chances are, judging by the error `simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`, you supplied the base URL of your Nextcloud server, and not the URL provided on the settings page in the Nextcloud Music app.

For example, on my system (running Nextcloud 24.0.1, Music app version 1.5.2) the URL is https://my-nextcloud-domain/apps/music/subsonic

**Comment by jasondunsmore** [comment]
I received this error when I copied the subsonic URL from nextcloud and it had a space at the end of the URL:

"https://my-nextcloud-domain/apps/music/subsonic "
