### ISSUE TITLE
Python Exception when trying to access playlists

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#340]
In GitLab by @cquike on Jul 18, 2022, 07:31

 I am trying sublime for the fist time and the connection to the server works, fine, I can browse albums and artists. However when I click in Playlists, even if I see all the playlists I have, when clicking on a particular one nothing happens and a python exception is raised in the console:

```
Traceback (most recent call last):
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/app.py", line 1039, in <lambda>
    lambda: self.window.update(
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/main.py", line 363, in update
    active_panel.update(app_config, force=force)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 117, in update
    self.playlist_list.update(app_config=app_config, force=force)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 232, in update
    self.update_list(app_config=app_config, force=force)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/util.py", line 435, in wrapper
    result.add_done_callback(
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/adapters/manager.py", line 151, in add_done_callback
    fn(self, *args)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/util.py", line 423, in future_callback
    fn()
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 273, in update_list
    util.diff_model_store(self.playlists_store, new_store)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/sublime_music/ui/util.py", line 166, in diff_model_store
    diff = DeepDiff(old_store, new_store)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 296, in __init__
    self._diff(root, parents_ids=frozenset({id(t1)}), _original_type=_original_type)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 1351, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 594, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 713, in _diff_iterable_in_order
    self._diff(next_level, parents_ids_added)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 1354, in _diff
    self._diff_obj(level, parents_ids)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 407, in _diff_obj
    self._diff_dict(
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 547, in _diff_dict
    self._diff(next_level, parents_ids_added)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 1351, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 594, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 713, in _diff_iterable_in_order
    self._diff(next_level, parents_ids_added)
  File "/scratch/home/cgarcia/.local/lib/python3.10/site-packages/deepdiff/diff.py", line 1338, in _diff
    elif isinstance(level.t1, Mapping):
  File "/usr/lib64/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
AttributeError: __class__
```

I have seen this problem with both the debian package in debian testing as well as with a pip installation in Fedora.
My subsonic server is actually an ampache server with the subsonic API enabled. I can use the subsonic API including browsing the playlist with other clients like D-Sub in Android or strawberry in Linux without problems.

**Comment by sumnerevans** [comment]
In GitLab by @cquike on Sep 8, 2022, 08:02

I will close this issue since MR !76 has already fixed the issues.
