### ISSUE TITLE
Can't launch sublime-music after pip install on fedora 36

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#341]
In GitLab by @ksdrummer on Jul 19, 2022, 17:06

Hi,

I'm an happy user of sublime-music on my arch laptop. It's such a great app! :clap: 

I just got a new tablet running fedora 36 and I installed sublime-music using pip.

- sublime-music doesn't show up in my apps (there is nothing in .local/share/applications nor in /usr/share/applications). I don't know if it is expected since I never installed anything from pip. This is more a question than an issue, I can create the .desktop file myself
- the issue: when I run sublime-text from the terminal, I get the following error:

```
$ sublime-text
Traceback (most recent call last):
  File "/home/user/.local/bin/sublime-music", line 5, in <module>
    from sublime_music.__main__ import main
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/__main__.py", line 14, in <module>
    from .app import SublimeMusicApp
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/app.py", line 48, in <module>
    from .dbus import dbus_propagate, DBusManager
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/dbus/__init__.py", line 1, in <module>
    from .manager import dbus_propagate, DBusManager
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/dbus/manager.py", line 13, in <module>
    from ..players import PlayerManager
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/players/__init__.py", line 1, in <module>
    from .manager import PlayerDeviceEvent, PlayerEvent, PlayerManager
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/players/manager.py", line 7, in <module>
    from .mpv import MPVPlayer  # noqa: F401
  File "/home/user/.local/lib/python3.10/site-packages/sublime_music/players/mpv.py", line 5, in <module>
    import mpv
  File "/home/user/.local/lib/python3.10/site-packages/mpv.py", line 49, in <module>
raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```

I'm using python3.10, maybe this is related.

I tried to manually install python-mpv but it already was installed as a dependency:

```
$ pip install python-mpv
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-mpv in ./.local/lib/python3.10/site-packages (0.5.2)
```

A little help would be much appreciated, I mostly bought this tablet to access my music at university.
Anyway, thank you so much for the awesome app!

**Comment by sumnerevans** [comment]
Probably need to install either libmpv or libmpv-dev.

**Comment by sumnerevans** [comment]
In GitLab by @ksdrummer on Jul 20, 2022, 21:08

Thank you for your reply!

For those who wanna now the fix, on fedora you need to user RPM fusion (free) repositories to install the following package : mpv-libs

Also, here is my desktop file in someone wonder how to make the app appear in your app list.
I downloaded the icon from gitlab and put it in .icons/sublime-music.png
then I created this file (or you can use a menu editor like menulibre)

**~/.local/share/applications/sublime-music.desktop**

```[Desktop Entry]
Version=1.1
Type=Application
Name=Sublime Music
Comment="WRITE WHATEVER DESCRIPTION YOU WANT"
Icon=/home/MYUSERNAME/.icons/sublime-music.png
Exec=sublime-music
Actions=
Categories=AudioVideo;Player;
```

Again, thank you so much for the hint!
