### ISSUE TITLE
Traceback on UI initialization, and fronzen "current playing" block (the bottom left part)

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#345]
In GitLab by @adam900710 on Sep 12, 2022, 02:31

The traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sublime_music/app.py", line 1039, in <lambda>
    lambda: self.window.update(
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/main.py", line 363, in update
    active_panel.update(app_config, force=force)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 117, in update
    self.playlist_list.update(app_config=app_config, force=force)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 232, in update
    self.update_list(app_config=app_config, force=force)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/util.py", line 435, in wrapper
    result.add_done_callback(
  File "/usr/lib/python3.10/site-packages/sublime_music/adapters/manager.py", line 151, in add_done_callback
    fn(self, *args)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/util.py", line 423, in future_callback
    fn()
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 273, in update_list
    util.diff_model_store(self.playlists_store, new_store)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/util.py", line 166, in diff_model_store
    diff = DeepDiff(old_store, new_store)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 296, in __init__
    self._diff(root, parents_ids=frozenset({id(t1)}), _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1351, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 594, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 713, in _diff_iterable_in_order
    self._diff(next_level, parents_ids_added)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1354, in _diff
    self._diff_obj(level, parents_ids)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 407, in _diff_obj
    self._diff_dict(
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 547, in _diff_dict
    self._diff(next_level, parents_ids_added)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1351, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 594, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 713, in _diff_iterable_in_order
    self._diff(next_level, parents_ids_added)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1338, in _diff
    elif isinstance(level.t1, Mapping):
  File "/usr/lib/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
AttributeError: __class__
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sublime_music/app.py", line 1039, in <lambda>
    lambda: self.window.update(
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/main.py", line 363, in update
    active_panel.update(app_config, force=force)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 117, in update
    self.playlist_list.update(app_config=app_config, force=force)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 232, in update
    self.update_list(app_config=app_config, force=force)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/util.py", line 435, in wrapper
    result.add_done_callback(
  File "/usr/lib/python3.10/site-packages/sublime_music/adapters/manager.py", line 151, in add_done_callback
    fn(self, *args)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/util.py", line 423, in future_callback
    fn()
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/playlists.py", line 273, in update_list
    util.diff_model_store(self.playlists_store, new_store)
  File "/usr/lib/python3.10/site-packages/sublime_music/ui/util.py", line 166, in diff_model_store
    diff = DeepDiff(old_store, new_store)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 296, in __init__
    self._diff(root, parents_ids=frozenset({id(t1)}), _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1351, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 594, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 713, in _diff_iterable_in_order
    self._diff(next_level, parents_ids_added)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1354, in _diff
    self._diff_obj(level, parents_ids)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 407, in _diff_obj
    self._diff_dict(
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 547, in _diff_dict
    self._diff(next_level, parents_ids_added)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1351, in _diff
    self._diff_iterable(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 594, in _diff_iterable
    self._diff_iterable_in_order(level, parents_ids, _original_type=_original_type)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 713, in _diff_iterable_in_order
    self._diff(next_level, parents_ids_added)
  File "/usr/lib/python3.10/site-packages/deepdiff/diff.py", line 1338, in _diff
    elif isinstance(level.t1, Mapping):
  File "/usr/lib/python3.10/abc.py", line 119, in __instancecheck__
    return _abc_instancecheck(cls, instance)
AttributeError: __class__
```

The result is, the bottom left corner, which normally shows the currently playing music (along with its album name, singer) never got refreshed.

**Comment by sumnerevans** [comment]
In GitLab by @adam900710 on Sep 12, 2022, 02:34

Forgot to mention other info:

Distro: Archlinux
Package version: sublime-music 0.11.16-2 (AUR)

**Comment by sumnerevans** [comment]
In GitLab by @cquike on Sep 15, 2022, 04:48

I think this is a duplicate of issue #340. There is already a fix in !76 merged in master. However as far as I can see there is no release package that has the fix included, so probably for the time being the only chance is to run it from source.

**Comment by sumnerevans** [comment]
In GitLab by @adam900710 on Sep 15, 2022, 05:44

Thanks for pointing out the correct fix.

Unfortunately the git AUR version failed to compile (looks like a packaging error).

Thankfully the fix is small enough that I can apply it to the python file directly, and it works now!

Just need to wait for the next release.
