### ISSUE TITLE
current_album_search_query field in UIState class needs to use default_factory to be compatible with Python 3.11

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#346]
In GitLab by @danhansen on Sep 20, 2022, 10:55

When running under python 3.11, I see a crash and the following backtrace when launching sublime:

```
Traceback (most recent call last):
  File "/home/dhansen/.local/bin/sublime-music", line 5, in <module>
    from sublime_music.__main__ import main
  File "/home/dhansen/.local/lib/python3.11/site-packages/sublime_music/__main__.py", line 14, in <module>
    from .app import SublimeMusicApp
  File "/home/dhansen/.local/lib/python3.11/site-packages/sublime_music/app.py", line 38, in <module>
    from .adapters import (
  File "/home/dhansen/.local/lib/python3.11/site-packages/sublime_music/adapters/__init__.py", line 11, in <module>
    from .manager import AdapterManager, DownloadProgress, Result, SearchResult
  File "/home/dhansen/.local/lib/python3.11/site-packages/sublime_music/adapters/manager.py", line 33, in <module>
    from sublime_music.config import ProviderConfiguration
  File "/home/dhansen/.local/lib/python3.11/site-packages/sublime_music/config.py", line 12, in <module>
    from .ui.state import UIState
  File "/home/dhansen/.local/lib/python3.11/site-packages/sublime_music/ui/state.py", line 41, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'sublime_music.adapters.adapter_base.AlbumSearchQuery'> for field current_album_search_query is not allowed: use default_factory
```

A bit of googling reveals that a change like this should address the issue:

```
diff --git a/sublime_music/ui/state.py b/sublime_music/ui/state.py
index 72dd258..76acecc 100644
--- a/sublime_music/ui/state.py
+++ b/sublime_music/ui/state.py
@@ -87,11 +87,12 @@ class UIState:
         def __init__(self):
             self.name = "Rock"
 
-    current_album_search_query: AlbumSearchQuery = AlbumSearchQuery(
-        AlbumSearchQuery.Type.RANDOM,
-        genre=_DefaultGenre(),
-        year_range=this_decade(),
-    )
+    current_album_search_query: AlbumSearchQuery = field(
+        default_factory = lambda: AlbumSearchQuery(
+            AlbumSearchQuery.Type.RANDOM,
+            genre=UIState._DefaultGenre(),
+            year_range=this_decade(),
+       ))
 
     active_playlist_id: Optional[str] = None
```

**Comment by sumnerevans** [comment]
In GitLab by @baldurmen on Dec 1, 2022, 12:27

I confirm this is an issue with Python 3.11 for Debian and that this patch does fix the testsuite failure we were having.

To make things easier for @sumnerevans , I'll take the liberty of sending @danhansen 's patch as a MR :)
