### ISSUE TITLE
Sublime crashes at launch

### ISSUE THREAD

**Issue by Estebiu** [sublime-music/sublime-music-python#414]
I'm not very sure what this means, so I hope someone will be kind enough to help me.
´´´sublime-music
Traceback (most recent call last):
  File "/usr/bin/sublime-music", line 5, in <module>
    from sublime_music.__main__ import main
  File "/usr/lib/python3.11/site-packages/sublime_music/__main__.py", line 14, in <module>
    from .app import SublimeMusicApp
  File "/usr/lib/python3.11/site-packages/sublime_music/app.py", line 36, in <module>
    from .adapters import (
  File "/usr/lib/python3.11/site-packages/sublime_music/adapters/__init__.py", line 11, in <module>
    from .manager import AdapterManager, DownloadProgress, Result, SearchResult
  File "/usr/lib/python3.11/site-packages/sublime_music/adapters/manager.py", line 33, in <module>
    from sublime_music.config import ProviderConfiguration
  File "/usr/lib/python3.11/site-packages/sublime_music/config.py", line 8, in <module>
    import dataclasses_json
ModuleNotFoundError: No module named 'dataclasses_json' ´´´

I've installed python 3.8 but that doesn't change anything. I'm using sublime-music-git from the AUR.

**Comment by sumnerevans** [comment]
is dataclasses-json installed for the correct version of python?

**Comment by edwargix** [comment]
@Estebiu are you still facing this issue?  The sublime-music and dataclasses-json AUR packages were both upgraded a week ago to support Python 3.11 and Sublime Music v0.12.0
