### ISSUE TITLE
Trying to run sublime-music via the AUR pkg throws an exception

### ISSUE THREAD

**Issue by sumnerevans** [sublime-music/sublime-music-python#65]
In GitLab by @edwargix on Oct 30, 2019, 16:20

```
$ sublime-music 
Traceback (most recent call last):
  File "/usr/bin/sublime-music", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gobject' distribution was not found and is required by sublime-music
```

**Comment by sumnerevans** [comment]
In GitLab by @edwargix on Nov 16, 2019, 13:01

The error is now complaining about `python-mpv`
```
Traceback (most recent call last):
  File "/usr/bin/sublime-music", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-mpv' distribution was not found and is required by sublime-music
```

**Comment by sumnerevans** [comment]
In GitLab by @edwargix on Nov 16, 2019, 13:02

which of course is weird because `python-mpv` is listed as a dependency in the PKGBUILD

**Comment by sumnerevans** [comment]
In GitLab by @edwargix on Nov 16, 2019, 13:20

Nevermind, if I `yay -Rs sublime-music` and re-install with `yay -S sublime-music` (and clean build all of the dependencies), running `sublime-music` yields the initial error message.

**Comment by sumnerevans** [comment]
Fixed this. The `gobject` dependency was the wrong one in `setup.py` it just needs `PyGobject`.

**Comment by sumnerevans** [comment]
closed
